version: "3.8"

services:
  social-api-prod:
    container_name: social-api-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: build_stage
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start
    env_file:
      - .env
