version: "3.8"

services:
  social-api-prod:
    container_name: social-api-prod
    build:
      context: ../../
      dockerfile: docker/social-api-prod/Dockerfile
      target: build_stage
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3100:3100"
    command: npm run start
