version: "3.8"

services:
  social-api-prod:
    container_name: social-api-prod
    build:
      context: ../../
      dockerfile: docker/social-api-prod/Dockerfile
      target: build_stage
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:
volumes:
  pgdata:
