version: "3.8"

services:
  social-api-prod:
    container_name: social-api-prod
    build:
      context: ../../
      dockerfile: docker/social-api-prod/Dockerfile
      target: build_stage
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3100:3100
    command: npm run start
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:
volumes:
  pgdata:
